#!/usr/bin/env bash
# install.sh — точка входа curl|bash для установки naive-panel.
#
# Использование:
#   curl -fsSL https://raw.githubusercontent.com/OWNER/naive-panel/main/install.sh | sudo bash
#
# Также используется внутри для:
#   install.sh --self-update   — пересобрать /usr/local/bin/naive из текущего репо

set -euo pipefail

REPO_URL="${NAIVE_PANEL_REPO:-https://github.com/mat-674/naive-panel.git}"
PANEL_DIR="${NAIVE_PANEL_DIR:-/opt/naive-panel}"
BIN_OUT="${NAIVE_BIN_DIR:-/usr/local/bin}/naive"

# --- общие проверки ---

require_root() {
  (( EUID == 0 )) || { printf "must be run as root (use sudo)\n" >&2; exit 1; }
}

detect_distro() {
  if [[ ! -f /etc/os-release ]]; then
    printf "unknown\n"; return 1
  fi
  . /etc/os-release
  case "${ID:-unknown}" in
    ubuntu|debian) printf "%s\n" "$ID" ;;
    *) printf "unsupported:%s\n" "${ID:-unknown}" ;;
  esac
}

# --- склейка naive + lib/*.sh в один файл ---

build_panel_binary() {
  local panel_dir="$1" out="$2"
  local tmp
  tmp=$(mktemp)

  # Шапка
  cat > "$tmp" <<'HEADER'
#!/usr/bin/env bash
# Auto-generated by naive-panel/install.sh — do not edit by hand.
set -euo pipefail
NAIVE_PANEL_DIR="${NAIVE_PANEL_DIR:-/opt/naive-panel}"
# Source'им lib/*.sh напрямую из репо. common.sh + config.sh первыми — от них
# зависят все остальные модули (NAIVE_* пути, логгер, prompt); glob-порядок
# не гарантирован.
if [[ -d "$NAIVE_PANEL_DIR/lib" ]]; then
  # shellcheck source=lib/common.sh
  source "$NAIVE_PANEL_DIR/lib/common.sh"
  # shellcheck source=lib/config.sh
  source "$NAIVE_PANEL_DIR/lib/config.sh"
  for f in "$NAIVE_PANEL_DIR/lib/"*.sh; do
    [[ -f "$f" ]] || continue
    case "$(basename "$f")" in
      common.sh|config.sh) ;;
      *) source "$f" ;;
    esac
  done
fi

HEADER

  # Тело диспетчера (после source'а модулей, чтобы можно было перекрыть stub'ы)
  cat "$panel_dir/naive" >> "$tmp"

  install -m 0755 "$tmp" "$out"
  rm -f "$tmp"
  printf "binary: %s\n" "$out"
}

# --- установка systemd unit + logrotate ---

install_systemd() {
  local panel_dir="$1"
  printf "==> Installing systemd unit + logrotate\n"

  install -m 0644 "$panel_dir/templates/systemd/naive-caddy.service" /etc/systemd/system/naive-caddy.service
  install -m 0644 "$panel_dir/templates/systemd/naive-logrotate"    /etc/logrotate.d/naive

  systemctl daemon-reload
  printf "  systemd unit: /etc/systemd/system/naive-caddy.service\n"
  printf "  logrotate:    /etc/logrotate.d/naive\n"
}

# --- main ---

case "${1:-install}" in
  --build-naive|--self-update)
    require_root
    [[ -d "$PANEL_DIR/lib" ]] || { printf "panel dir not found: %s\n" "$PANEL_DIR" >&2; exit 1; }
    printf "==> Building %s from %s\n" "$BIN_OUT" "$PANEL_DIR"
    build_panel_binary "$PANEL_DIR" "$BIN_OUT"
    printf "[+] done — run: %s\n" "$BIN_OUT"
    exit 0
    ;;
  install|--bootstrap)
    require_root
    distro=$(detect_distro)
    case "$distro" in
      ubuntu|debian) ;;
      *) printf "unsupported distro: %s (only Ubuntu/Debian)\n" "$distro" >&2; exit 1 ;;
    esac

    printf "==> Installing naive-panel on %s\n" "$distro"

    # 1) Базовые пакеты
    apt-get update -qq
    apt-get install -y --no-install-recommends \
      ca-certificates curl git jq qrencode ufw vnstat openssl

    # 2) Клонируем репо (или используем уже существующее)
    if [[ ! -d "$PANEL_DIR/.git" ]]; then
      printf "==> Cloning %s → %s\n" "$REPO_URL" "$PANEL_DIR"
      git clone --depth 1 "$REPO_URL" "$PANEL_DIR"
    fi

    # 3) Склеиваем бинарь
    build_panel_binary "$PANEL_DIR" "$BIN_OUT"

    # 4) systemd + logrotate
    install_systemd "$PANEL_DIR"

    # 5) Подсказка дальнейших шагов
    cat <<EOF

================================================================
 Installation complete.
================================================================

Next steps:

  sudo $BIN_OUT install    # interactive installer (TLS, user, masquerade)

Or, if you prefer to do it manually, edit /etc/naive/naive.conf
and run:

  sudo $BIN_OUT

EOF
    exit 0
    ;;
  *)
    printf "Usage: %s install|--build-naive\n" "$0" >&2
    exit 2
    ;;
esac